name: .NET Core

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Install dependencies
      run: dotnet restore HTMLconvert.sln
    - name: Build
      run: dotnet build HTMLconvert.sln --configuration Release --no-restore 
    - name: Tests
      run: dotnet test Tests/Tests.csproj
    - name: Publish HTMLconvert
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: HTMLconvert/HTMLconvert.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
