name: Publish Nuget package
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Parse Version
    - uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: version
      with:
        proj-path: YourProject/YourProject.csproj
    - run: echo "${{steps.version.outputs.version}}"
    - run: echo "${{steps.version.outputs.version-prefix}}" 
    - run: echo "${{steps.version.outputs.version-suffix}}" 
    - run: echo "${{steps.version.outputs.package-version}}" 
    - run: echo "${{steps.version.outputs.assembly-version}}" 
    - run: echo "${{steps.version.outputs.file-version}}" 
    - run: echo "${{steps.version.outputs.informational-version}}"
